version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - CLOUDINARY_NAME=drlsewft4
      - CLOUDINARY_API_KEY=797196338817195
      - CLOUDINARY_API_SECRET=ihK5p_Ytv8jbvSTJa7131MB8Z88
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
